---
- name: Upgrade all packages with sudo bash
  hosts: all
  become: yes
  tasks:
    - name: Run apt update and upgrade with sudo bash
      shell: |
        sudo bash -c 'apt update && apt upgrade -y'
