---
- name: Install Nala and update .bashrc with aliases
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Update the package index
      apt:
        update_cache: yes

    - name: Install Nala package
      apt:
        name: nala
        state: present

    - name: Get a list of home directories
      command: "ls /home"
      register: home_dirs

    - name: Append alias lines to .bashrc for each user
      lineinfile:
        path: "/home/{{ user }}/.bashrc"
        line: "{{ item }}"
        create: yes
        state: present
        insertafter: EOF
      with_items:
        - "# package manager alias"
        - "# apt was changed to apt# in /usr/bin to allow this command"
        - "alias apt='nala'"
        - "# The white space after the o in sudo is intentional"
        - "alias sudo='sudo '"
      loop_control:
        loop_var: user
      with_items: "{{ home_dirs.stdout }}"
