---
- name: Install Nala and update .bashrc with aliases
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Update the package index
      apt:
        update_cache: yes

    - name: Install Nala package
      apt:
        name: nala
        state: present

    - name: Get a list of home directories
      command: "ls /home"
      register: home_dirs

    - name: Add alias lines to the end of .bashrc for each user
      blockinfile:
        path: "/home/{{ user }}/.bashrc"
        block: |
          # package manager alias
          # apt was changed to apt# in /usr/bin to allow this command
          alias apt='nala'
          # The white space after the o in sudo is intentional
          alias sudo='sudo '
        create: yes
      loop: "{{ home_dirs.stdout_lines }}"
      loop_control:
        loop_var: user

    - name: Source .bashrc to make aliases immediately available
      shell: "source /home/{{ user }}/.bashrc"
      loop: "{{ home_dirs.stdout_lines }}"
      loop_control:
        loop_var: user
      ignore_errors: yes
