---
- name: Run Proxmox Backup Server setup script on all hosts using Bullseye repository
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Create the setup script on the remote host
      copy:
        dest: /tmp/setup_proxmox_server_repo.sh
        content: |
          #!/bin/bash
          
          # Script to add Proxmox Backup Server repository (No-Subscription) without installing the client
          # Using Bullseye repository

          # Function to check if the script is run as root
          check_root() {
            if [ "$EUID" -ne 0 ]; then
              echo "This script must be run as root. Exiting..."
              exit 1
            fi
          }

          # Function to add the Proxmox GPG key
          add_gpg_key() {
            echo "Adding Proxmox GPG key..."
            wget https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
            if [ $? -ne 0 ]; then
              echo "Failed to add Proxmox GPG key."
              exit 1
            fi
            echo "Proxmox GPG key added successfully."
          }

          # Function to add the Proxmox Backup Server No-Subscription repository (Bullseye)
          add_repository() {
            echo "Adding Proxmox Backup Server No-Subscription repository for Bullseye..."
            echo "deb [signed-by=/etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg] http://download.proxmox.com/debian/pbs bullseye pbs-no-subscription" | tee /etc/apt/sources.list.d/proxmox-backup-server.list
            if [ $? -ne 0 ]; then
              echo "Failed to add Proxmox Backup Server repository."
              exit 1
            fi
            echo "Proxmox Backup Server No-Subscription repository added successfully."
          }

          # Main script execution
          check_root
          add_gpg_key
          add_repository

          echo "Proxmox Backup Server repository setup completed!"
        
        mode: '0755'

    - name: Run the setup Proxmox Backup Server script
      command: /tmp/setup_proxmox_server_repo.sh
      become: true

    - name: Clean up the script after execution
      file:
        path: /tmp/setup_proxmox_server_repo.sh
        state: absent
