---
- name: Run Proxmox Backup Server setup script as root on all hosts using Bullseye repository
  hosts: all
  become: true
  become_user: root  # Explicitly become root user
  tasks:
    - name: Download libssl1.1 package
      ansible.builtin.get_url:
        url: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
        dest: /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb

    - name: Install libssl1.1 package
      ansible.builtin.shell: |
        dpkg -i /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
        apt-get install -f -y  # This will fix any missing dependencies
      become: true

    - name: Create the setup script on the remote host
      ansible.builtin.copy:
        dest: /tmp/setup_proxmox_server_repo.sh
        content: |
          #!/bin/bash
          
          # Script to add Proxmox Backup Server repository (No-Subscription) without installing the client
          # Using Bullseye repository

          # Function to check if the script is run as root
          check_root() {
            if [ "$EUID" -ne 0 ]; then
              echo "This script must be run as root. Exiting..."
              exit 1
            fi
          }

          # Function to add the Proxmox GPG key
          add_gpg_key() {
            echo "Adding Proxmox GPG key..."
            wget https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
            if [ $? -ne 0 ]; then
              echo "Failed to add Proxmox GPG key."
              exit 1
            fi
            echo "Proxmox GPG key added successfully."
          }

          # Function to add the Proxmox Backup Server No-Subscription repository (Bullseye)
          add_repository() {
            echo "Adding Proxmox Backup Server No-Subscription repository for Bullseye..."
            echo "deb [signed-by=/etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg] http://download.proxmox.com/debian/pbs bullseye pbs-no-subscription" | tee /etc/apt/sources.list.d/proxmox-backup-server.list
            if [ $? -ne 0 ]; then
              echo "Failed to add Proxmox Backup Server repository."
              exit 1
            fi
            echo "Proxmox Backup Server No-Subscription repository added successfully."
          }

          # Main script execution
          check_root
          add_gpg_key
          add_repository

          echo "Proxmox Backup Server repository setup completed!"
        
        mode: '0755'

    - name: Run the setup Proxmox Backup Server script
      ansible.builtin.shell: /tmp/setup_proxmox_server_repo.sh
      become: true

    - name: Clean up the script after execution
      ansible.builtin.file:
        path: /tmp/setup_proxmox_server_repo.sh
        state: absent

    - name: Update apt package lists after adding Proxmox repository
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache is valid for 1 hour

    - name: Clean up the libssl1.1 package
      ansible.builtin.file:
        path: /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
        state: absent
